apiVersion: v1
kind: Pod
metadata:
  name: new-nfs-share-pod
spec:
  containers:
    - name: hello-manila
      image: k8s.gcr.io/echoserver:1.4
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: new-nfs-share-pvc
        readOnly: false
